server:
  contextPath: /solver

logging:
  level:
    com.maersk.kanpsack.solver: DEBUG

info:
  build:
    version: @project.version@
    number: @build.number@

endpoints:
  shutdown:
     sensitive: true
     enabled: true
