version: "2"
services:
  knapsack-solver:
        container_name: knapsack-solver
        build:
            context: ./knapsack-solver
            dockerfile: Dockerfile
        image: knapsack-solver:latest
        expose:
            - 8080
        ports:
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
        
    knapsack-optimizer-service:
        container_name: knapsack-optimizer-service
        build:
            context: ./knapsack-optimizer-service
            dockerfile: Dockerfile
        image: knapsack-optimizer-service:latest
        expose:
            - 9091
        ports:
            - target: 9091
              published: 9091
              protocol: tcp
              mode: host
        links:
            - knapsack-solver:knapsack-solver
        depends_on:
            - knapsack-solver
        
