version: "2"
services:
  knapsack-solver:
        container_name: knapsack-solver
        build:
            context: ./knapsack-solver
            dockerfile: Dockerfile
        image: gcr.io/protean-unity-193306/knapsack-solver:latest
        expose:
            - "8080"
        ports:
            - "8080:8080"
  knapsack-optimizer-service:
        container_name: knapsack-optimizer-service
        build:
            context: ./knapsack-optimizer
            dockerfile: Dockerfile
        image: gcr.io/protean-unity-193306/knapsack-optimizer-service:latest
        expose:
            - 6543
        ports:
            - "6543:6543"
        links:
            - knapsack-solver:knapsack-solver
        depends_on:
            - knapsack-solver
