server:
  contextPath: /knapsack
  port: 6543

logging:
  level:
    com.maersk.fse.kanpsack: DEBUG

info:
  build:
    version: @project.version@
    number: @build.number@
    
endpoints:
   shutdown:
     sensitive: true
     enabled: true
    
solver:
   app:
      user: app
      key: aniders